# Requires nightly build of rustfmt
unstable_features = true

# <https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#preserve>


edition = "2024"
# The edition of the Rust Style Guide to follow
style_edition = "2024"

# Format code blocks in documentation
format_code_in_doc_comments = true

format_generated_files = true

format_macro_bodies = true

# Force a consistent style with macro patterns
format_macro_matchers = true

# Keep string literals under the `max_width` with a backslash
format_strings = true
hex_literal_case = "Lower"

# Force imports to be grouped by deepest module per crate
imports_granularity = "Module"
# match_block_trailing_comma = true

# Convert `/* */` comments to `//` comments where possible.
normalize_comments = true

# When the last expression with group delimiters is too long, instead of
# breaking and indenting after each argument, allow the content of the last
# expression to format vertically with indentation.
overflow_delimited_expr = true

# In an `impl` block, `type` and `const` are put first, then macros and methods.
reorder_impl_items = true

# Where possible, turn `x: x` into `x`.
use_field_init_shorthand = true

use_small_heuristics = "Max"

max_width = 80

wrap_comments = true

# Enforce line endings, though this should be handled by Git
newline_style = "Unix"
# Group stock, external, and current crate imports together with newline

group_imports = "StdExternalCrate"

# Allow a leading pipe before match arms
# <https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#preserve>
match_arm_leading_pipes = "Preserve"
